name: my_portfolio
description: Learning Flutter Web by creating a Portfolio App to display my projects.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  url_strategy: ^0.2.0
  cupertino_icons: ^1.0.2
  responsive_builder: ^0.4.1
  flutter_screenutil: ^5.0.0
  flutter_svg: ^0.21.0+1
  animated_text_kit: ^4.1.1
  url_launcher: ^6.0.3
  auto_size_text: 3.0.0-nullsafety.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Thin.ttf
          weight: 100
        - asset: assets/fonts/Poppins-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Poppins-Black.ttf
          weight: 900
    - family: Freestyle
      fonts:
        - asset: assets/fonts/FREESCPT.TTF
    - family: Raleway
      fonts:
        - asset: assets/fonts/Raleway-Italic-VariableFont_wght.ttf
        - asset: assets/fonts/Raleway-VariableFont_wght.ttf
